#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
APP_PATH=$0

# Need this for relative symlinks.
while [ -h "$APP_PATH" ] ; do
  ls=$(ls -ld "$APP_PATH")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    APP_PATH="$link"
  else
    APP_PATH=$(dirname "$APP_PATH")"/$link"
  fi
 done

APP_HOME=$(cd "$(dirname "$APP_PATH")" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

WRAPPER_JAR=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
CLASSPATH=$WRAPPER_JAR

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# If the wrapper JAR is missing, fall back to a system Gradle installation.
if [ ! -f "$WRAPPER_JAR" ] ; then
    if command -v gradle >/dev/null 2>&1; then
        exec gradle "$@"
    fi
    die "ERROR: Gradle wrapper JAR is missing at $WRAPPER_JAR and no system 'gradle' command was found."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n "$MAX_FD" >/dev/null 2>&1 || warn "Could not set maximum file descriptor limit: $MAX_FD"
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command.
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, GRADLE_OPTS environment variables.
#   * For Cygwin or MSYS, switch paths to Windows format before running java
#   * For alld env vars, replace \r with 
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg in "$@" ; do
        if expr "$arg" : '.*' >/dev/null ; then
            arg=$(printf "%s" "$arg" | sed 's/\/\\\\/g')
            if expr "$arg" : '.*' >/dev/null ; then
                arg=$(printf "%s" "$arg" | sed 's/\\"/\\\"/g')
            fi
            eval "arg=\"$arg\""
        fi
        # Aiyiyi, symlinks can cause you to blow up.
        # The target of the symlink can be relative.
        # Please inform the Gradle developers if you encounter this:
        #   https://github.com/gradle/gradle/issues/1279
        eval "set -- \"$@\" \"$arg\""
    done
fi

# Escape application args
save () {
    for i do printf '%s\n' "$i" | sed "s/'/'\\''/g;1s/^/'/;$s/\$/'/"; done
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, following the shell quoting and substitution rules
# shellcheck disable=SC2086
set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$APP_HOME" || exit
fi

exec "$JAVACMD" "$@"
